# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb01a1929469ac21923b1282e0dd2e223c25025187286105b30fc076bf4f82945e8b26d59444149524ee392939399baf5c8fd1bdb9e50b4d867f8436e48fd081

test:
  secret_key_base: d8ded155621c044ca8da11160c24f6d7db546f2de95490226ce8817db6c54f54217c94ef0058124bc8a843cd0308b44c236724860b7d2687c23942f4af882004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
